//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBShare.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public int Id { get; set; }
        public Nullable<int> TokenId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Member_count { get; set; }
    
        public virtual Token Token { get; set; }
    }
}
